import { createContext, useContext, useMemo, useState } from "react";

const LanguageContext = createContext(null);

/* =========================================================
   BANGLA TRANSLATIONS
========================================================= */
const bn = {
  // --- NAVBAR & GLOBAL ---
  "Features": "ফিচারসমূহ",
  "Solutions": "সমাধানসমূহ",
  "Pricing": "মূল্য নির্ধারণ",
  "Resources": "রিসোর্স",
  "Log in": "লগ ইন",
  "Start free trial": "ফ্রি ট্রায়াল শুরু করুন",
  "Start free": "ফ্রি শুরু করুন",
  "Toggle navigation": "নেভিগেশন খুলুন",
  "Restaurant": "রেস্টুরেন্ট",
  "Student Visa Agency": "স্টুডেন্ট ভিসা এজেন্সি",
  "Visa Agency": "ভিসা এজেন্সি",
  "Business Manager": "বিজনেস ম্যানেজার",
  "Demo dashboard": "ডেমো ড্যাশবোর্ড",
  "Live preview": "লাইভ প্রিভিউ",
  "View all": "সব দেখুন",

  // --- HERO SECTION ---
  "Run your business.": "আপনার ব্যবসা পরিচালনা করুন।",
  "Grow it smarter.": "আরও স্মার্টভাবে বাড়ান।",
  "Watch 2-min demo": "২ মিনিটের ডেমো দেখুন",
  "AI business manager for restaurants and agencies": "রেস্টুরেন্ট ও এজেন্সির জন্য AI বিজনেস ম্যানেজার",
  "CRM, website and an AI business manager, in one simple platform.": "CRM, ওয়েবসাইট এবং একটি AI বিজনেস ম্যানেজার — সবই একটি সহজ প্ল্যাটফর্মে।",
  "Made for businesses in Bangladesh": "বাংলাদেশের ব্যবসার জন্য তৈরি",
  "Local payments": "স্থানীয় পেমেন্ট",
  "Sales": "বিক্রয়",
  "New order": "নতুন অর্ডার",
  "AI tip": "AI পরামর্শ",
  "Try a combo offer on Tuesday to improve repeat orders.": "রিপিট অর্ডার বাড়াতে মঙ্গলবার একটি কম্বো অফার চেষ্টা করুন।",

  // --- TRUST STRIP ---
  "Secure payments": "নিরাপদ পেমেন্ট",
  "Made for Bangladesh": "বাংলাদেশের জন্য তৈরি",
  "Secure payments and made for Bangladesh": "নিরাপদ পেমেন্ট এবং বাংলাদেশের জন্য তৈরি",

  // --- CHOOSE BUSINESS ---
  "Choose your business": "আপনার ব্যবসা নির্বাচন করুন",
  "Built around the way": "যেভাবে কাজ করে সেভাবেই",
  "your business works.": "তৈরি হয়েছে আপনার ব্যবসার জন্য।",
  "Start with the tools that fit your business today. Your choice will also be remembered when you create your BeezNest account.": "আজ আপনার ব্যবসার সাথে মানানসই টুল দিয়ে শুরু করুন। আপনার নির্বাচন BeezNest অ্যাকাউন্ট তৈরির সময়ও মনে রাখা হবে।",
  "Orders, customers, sales and your digital menu in one connected system.": "অর্ডার, কাস্টমার, বিক্রয় এবং ডিজিটাল মেনু — সব একটি সংযুক্ত সিস্টেমে।",
  "Track orders and daily sales": "অর্ডার ও দৈনিক বিক্রয় ট্র্যাক করুন",
  "QR ordering and digital menu": "QR অর্ডারিং ও ডিজিটাল মেনু",
  "AI insights for repeat customers": "রিপিট কাস্টমারদের জন্য AI ইনসাইট",
  "Keep applicants, documents, follow-ups and your pipeline organized.": "আবেদনকারী, ডকুমেন্ট, ফলো-আপ এবং পাইপলাইন সাজিয়ে রাখুন।",
  "Manage applicants and pipeline": "আবেদনকারী ও পাইপলাইন পরিচালনা করুন",
  "Keep documents and tasks organized": "ডকুমেন্ট ও কাজ সাজিয়ে রাখুন",
  "Follow up with leads using AI": "AI দিয়ে লিড ফলো-আপ করুন",
  "More business types coming soon": "আরও ব্যবসার ধরন শীঘ্রই আসছে",
  "We are building more tools for growing businesses across Bangladesh.": "বাংলাদেশের বর্ধনশীল ব্যবসার জন্য আমরা আরও টুল তৈরি করছি।",
  "New business tools": "নতুন ব্যবসার টুল",
  "More coming soon": "আরও শীঘ্রই আসছে",
  "Already know what you need?": "আপনার কী প্রয়োজন জানা আছে?",
  "Explore the features": "ফিচারগুলো দেখুন",
  "For restaurants": "রেস্টুরেন্টের জন্য",
  "For visa agencies": "ভিসা এজেন্সির জন্য",

  // --- MINI DASHBOARDS ---
  "Restaurant overview": "রেস্টুরেন্ট ওভারভিউ",
  "Visa pipeline": "ভিসা পাইপলাইন",
  "Agency": "এজেন্সি",
  "Orders": "অর্ডার",
  "Customers": "কাস্টমার",
  "Revenue": "রাজস্ব",
  "Sales overview": "বিক্রয় ওভারভিউ",
  "Last 7 days": "গত ৭ দিন",
  "New": "নতুন",
  "Processing": "প্রসেসিং",
  "Approved": "অনুমোদিত",
  "Recent applicants": "সাম্প্রতিক আবেদনকারী",
  "Student Visa": "স্টুডেন্ট ভিসা",
  "UK Application": "UK আবেদন",
  "Canada Study": "কানাডা স্টাডি",

  // --- PROBLEM TO SOLUTION ---
  "Problem to solution": "সমস্যা থেকে সমাধান",
  "Stop switching between tools.": "বারবার টুল পরিবর্তন করা বন্ধ করুন।",
  "Bring your CRM, website and business insights together in one simple platform.": "আপনার CRM, ওয়েবসাইট এবং ব্যবসায়িক ইনসাইট একটি সহজ প্ল্যাটফর্মে একত্রিত করুন।",
  "One connected platform": "একটি সংযুক্ত প্ল্যাটফর্ম",
  "Before": "আগে",
  "Too many tools.": "অতিরিক্ত টুল।",
  "Your business information is scattered across different places.": "আপনার ব্যবসার তথ্য বিভিন্ন জায়গায় ছড়িয়ে আছে।",
  "Notebook": "নোটবুক",
  "Spreadsheet": "স্প্রেডশিট",
  "Website": "ওয়েবসাইট",
  "CRM": "CRM",
  "Disconnected": "বিচ্ছিন্ন",
  "Too many tools, too many logins, and information that never stays in sync.": "অতিরিক্ত টুল, অতিরিক্ত লগইন, এবং তথ্য কখনোই সিঙ্কে থাকে না।",
  "After": "পরে",
  "One connected platform.": "একটি সংযুক্ত প্ল্যাটফর্ম।",
  "Everything works together so you can focus on growing your business.": "সবকিছু একসাথে কাজ করে, যাতে আপনি ব্যবসা বাড়াতে মনোযোগ দিতে পারেন।",
  "Business dashboard": "বিজনেস ড্যাশবোর্ড",
  "Leads": "লিড",
  "Growth": "গ্রোথ",
  "Connected": "সংযুক্ত",
  "AI Manager": "AI ম্যানেজার",
  "One dashboard. One connected system. One clearer view of your business.": "একটি ড্যাশবোর্ড। একটি সংযুক্ত সিস্টেম। আপনার ব্যবসার আরও স্পষ্ট দৃশ্য।",
  "Less switching.": "কম টুল বদলানো।",
  "More doing.": "বেশি কাজ করা।",
  "BeezNest brings the important parts of your business into one place.": "BeezNest আপনার ব্যবসার গুরুত্বপূর্ণ অংশগুলো এক জায়গায় নিয়ে আসে।",

  // --- HOW IT WORKS ---
  "How it works": "যেভাবে কাজ করে",
  "Get started in four": "চারটি সহজ ধাপে",
  "simple steps.": "শুরু করুন।",
  "From your first sign-up to a connected business workspace, BeezNest keeps the setup simple.": "প্রথম সাইন-আপ থেকে একটি সংযুক্ত ব্যবসায়িক ওয়ার্কস্পেস পর্যন্ত, BeezNest সেটআপ সহজ রাখে।",
  "Sign up": "সাইন আপ করুন",
  "Create your account and choose Restaurant or Student Visa Agency.": "আপনার অ্যাকাউন্ট তৈরি করুন এবং রেস্টুরেন্ট বা স্টুডেন্ট ভিসা এজেন্সি বেছে নিন।",
  "Tell us about your business": "আপনার ব্যবসা সম্পর্কে জানান",
  "Add the basic information BeezNest needs to understand your business.": "BeezNest আপনার ব্যবসা বুঝতে যে মৌলিক তথ্য প্রয়োজন, তা যোগ করুন।",
  "Set up your menu or pipeline": "আপনার মেনু বা পাইপলাইন সেটআপ করুন",
  "Add your menu, services, applicants, or pipeline in a few simple steps.": "কয়েকটি সহজ ধাপে আপনার মেনু, সেবা, আবেদনকারী বা পাইপলাইন যোগ করুন।",
  "Get your website and AI manager": "আপনার ওয়েবসাইট ও AI ম্যানেজার পান",
  "Launch your website and start asking your AI manager for business help.": "আপনার ওয়েবসাইট চালু করুন এবং AI ম্যানেজারকে ব্যবসায়িক সহায়তার জন্য জিজ্ঞাসা করুন।",
  "No complicated setup. Just follow the steps and start building.": "কোনো জটিল সেটআপ নেই। শুধু ধাপগুলো অনুসরণ করুন এবং শুরু করুন।",
  "Create your account": "আপনার অ্যাকাউন্ট তৈরি করুন",
  "Continue": "চালিয়ে যান",
  "Step 2": "ধাপ ২",
  "Your business": "আপনার ব্যবসা",
  "Business name": "ব্যবসার নাম",
  "Location": "অবস্থান",
  "Business details": "ব্যবসার বিবরণ",
  "Setup": "সেটআপ",
  "Your workspace": "আপনার ওয়ার্কস্পেস",
  "Menu": "মেনু",
  "Pipeline": "পাইপলাইন",
  "Setup progress": "সেটআপের অগ্রগতি",
  "80% complete": "৮০% সম্পন্ন",
  "Your business is ready": "আপনার ব্যবসা প্রস্তুত",
  "BeezNest dashboard": "BeezNest ড্যাশবোর্ড",
  "Live": "লাইভ",
  "Ask me about your business": "আপনার ব্যবসা সম্পর্কে জিজ্ঞাসা করুন",

  // --- FEATURE SHOWCASE ---
  "Feature showcase": "ফিচার প্রদর্শনী",
  "See what BeezNest can": "দেখুন BeezNest আপনার জন্য",
  "do for you.": "কী করতে পারে।",
  "Choose your business and explore the tools built around the way you work.": "আপনার ব্যবসা বেছে নিন এবং আপনার কাজের ধরন অনুযায়ী তৈরি টুলগুলো দেখুন।",
  "Restaurant tools": "রেস্টুরেন্ট টুল",
  "Visa agency tools": "ভিসা এজেন্সি টুল",
  "Built around your workflow": "আপনার ওয়ার্কফ্লো অনুযায়ী তৈরি",
  "Live product preview": "লাইভ প্রোডাক্ট প্রিভিউ",
  "Simple": "সহজ",
  "Easy to understand": "সহজে বোঝা যায়",
  "Works with your CRM": "আপনার CRM-এর সাথে কাজ করে",
  "Business-ready": "ব্যবসার জন্য প্রস্তুত",
  "Built for daily work": "দৈনন্দিন কাজের জন্য তৈরি",
  "Everything is designed to keep your business information in one connected place.": "সবকিছু এমনভাবে ডিজাইন করা হয়েছে যাতে আপনার ব্যবসার তথ্য এক জায়গায় সংযুক্ত থাকে।",

  // Feature titles & descriptions
  "Smart order management": "স্মার্ট অর্ডার ম্যানেজমেন্ট",
  "Keep orders, customers and daily sales organized from one place.": "এক জায়গা থেকে অর্ডার, কাস্টমার এবং দৈনিক বিক্রয় সাজিয়ে রাখুন।",
  "Profit per item": "প্রতি আইটেমের লাভ",
  "Understand which menu items are actually contributing to your business.": "কোন মেনু আইটেমগুলো আসলে আপনার ব্যবসায় অবদান রাখছে তা বুঝুন।",
  "QR table ordering": "QR টেবিল অর্ডারিং",
  "Let customers browse your menu and place orders from their table.": "কাস্টমারদের টেবিল থেকেই মেনু দেখা এবং অর্ডার করার সুযোগ দিন।",
  "Smart win-back SMS": "স্মার্ট উইন-ব্যাক SMS",
  "Reconnect with customers who have not visited recently.": "যেসব কাস্টমার সম্প্রতি আসেননি তাদের আবার ফিরিয়ে আনুন।",
  "AI business manager": "AI বিজনেস ম্যানেজার",
  "Ask questions about your restaurant and get useful business insights.": "আপনার রেস্টুরেন্ট সম্পর্কে প্রশ্ন করুন এবং প্রয়োজনীয় ব্যবসায়িক ইনসাইট পান।",
  "Student management": "স্টুডেন্ট ম্যানেজমেন্ট",
  "Keep student information, documents and application progress together.": "স্টুডেন্টের তথ্য, ডকুমেন্ট এবং আবেদনের অগ্রগতি একসাথে রাখুন।",
  "Lead tracking": "লিড ট্র্যাকিং",
  "Track new leads and move them through your agency pipeline.": "নতুন লিড ট্র্যাক করুন এবং আপনার এজেন্সি পাইপলাইনে এগিয়ে নিন।",
  "Follow-up automation": "ফলো-আপ অটোমেশন",
  "Keep follow-ups organized so important prospects do not get forgotten.": "ফলো-আপগুলো সাজিয়ে রাখুন যাতে গুরুত্বপূর্ণ সম্ভাবনাগুলো ভুলে না যায়।",
  "Website + CRM": "ওয়েবসাইট + CRM",
  "Keep your public website connected with the information in your CRM.": "আপনার পাবলিক ওয়েবসাইট CRM-এর তথ্যের সাথে সংযুক্ত রাখুন।",
  "Get quick answers about leads, students and your agency workflow.": "লিড, স্টুডেন্ট এবং আপনার এজেন্সি ওয়ার্কফ্লো সম্পর্কে দ্রুত উত্তর পান।",

  // Feature showcase visuals
  "Today": "আজ",
  "Active": "সক্রিয়",
  "Menu insights": "মেনু ইনসাইট",
  "Best seller": "বেস্ট সেলার",
  "Margin": "মার্জিন",
  "Trend": "ট্রেন্ড",
  "Up": "ঊর্ধ্বমুখী",
  "Table ordering": "টেবিল অর্ডারিং",
  "Scan & order": "স্ক্যান করুন ও অর্ডার করুন",
  "Table": "টেবিল",
  "Items": "আইটেম",
  "Order": "অর্ডার",
  "Preparing": "প্রস্তুত হচ্ছে",
  "Win-back campaign": "উইন-ব্যাক ক্যাম্পেইন",
  "Reconnect": "পুনঃসংযোগ",
  "Recent customer": "সাম্প্রতিক কাস্টমার",
  "No visit in 30 days": "৩০ দিনে কোনো ভিজিট নেই",
  "We miss you! Come back this week and enjoy a special offer from us.": "আমরা আপনাকে মিস করছি! এই সপ্তাহে ফিরে আসুন এবং আমাদের কাছ থেকে একটি বিশেষ অফার উপভোগ করুন।",
  "Campaign": "ক্যাম্পেইন",
  "Ready": "প্রস্তুত",
  "Ask your business": "আপনার ব্যবসাকে জিজ্ঞাসা করুন",
  "How can I get more repeat customers?": "আমি কীভাবে আরও রিপিট কাস্টমার পেতে পারি?",
  "Start by reviewing customers who have not returned recently. I can help you create a win-back campaign for them.": "যেসব কাস্টমার সম্প্রতি ফিরে আসেননি তাদের পর্যালোচনা করে শুরু করুন। আমি তাদের জন্য একটি উইন-ব্যাক ক্যাম্পেইন তৈরি করতে সাহায্য করতে পারি।",
  "Business-aware AI assistant": "ব্যবসা-সচেতন AI সহকারী",
  "Students": "স্টুডেন্ট",
  "Application pipeline": "আবেদন পাইপলাইন",
  "Review": "পর্যালোচনা",
  "Submitted": "জমা দেওয়া হয়েছে",
  "Lead pipeline": "লিড পাইপলাইন",
  "Keep every lead moving": "প্রতিটি লিড এগিয়ে নিন",
  "Follow-up": "ফলো-আপ",
  "Qualified": "যোগ্য",
  "Follow-ups": "ফলো-আপ",
  "Never miss a next step": "পরবর্তী ধাপ কখনো মিস করবেন না",
  "Call Rahim": "রহিমকে কল করুন",
  "Send documents": "ডকুমেন্ট পাঠান",
  "Check application": "আবেদন পরীক্ষা করুন",
  "Website": "ওয়েবসাইট",
  "Connected to your CRM": "আপনার CRM-এর সাথে সংযুক্ত",
  "Today · 3:00 PM": "আজ · বিকাল ৩:০০",
  "Tomorrow · 10:30 AM": "আগামীকাল · সকাল ১০:৩০",
  "Friday · 11:00 AM": "শুক্রবার · সকাল ১১:০০",

  // --- SPECIAL FEATURES ---
  "Special features": "বিশেষ ফিচার",
  "Small details that make": "ছোট ছোট সুবিধা যা",
  "a big difference.": "বড় পার্থক্য তৈরি করে।",
  "Useful tools that turn BeezNest from a simple dashboard into a smarter business workspace.": "প্রয়োজনীয় টুল যা BeezNest-কে একটি সহজ ড্যাশবোর্ড থেকে স্মার্ট ব্যবসায়িক ওয়ার্কস্পেসে পরিণত করে।",
  "See which products bring the strongest margins and make smarter menu decisions.": "কোন পণ্যগুলো সবচেয়ে বেশি মার্জিন আনে তা দেখুন এবং আরও স্মার্ট মেনু সিদ্ধান্ত নিন।",
  "Let customers scan, browse and order directly from their table.": "কাস্টমারদের টেবিল থেকেই স্ক্যান, ব্রাউজ এবং অর্ডার করার সুযোগ দিন।",
  "Give your team and customers a familiar experience in both languages.": "আপনার টিম এবং কাস্টমারদের উভয় ভাষায় পরিচিত অভিজ্ঞতা দিন।",
  "Weekly AI report": "সাপ্তাহিক AI রিপোর্ট",
  "Get a simple weekly summary of useful business signals and trends.": "প্রতি সপ্তাহে প্রয়োজনীয় ব্যবসায়িক সংকেত ও ট্রেন্ডের সহজ সারাংশ পান।",
  "Website synced with CRM": "CRM-এর সাথে সিঙ্ক করা ওয়েবসাইট",
  "Keep your website and business information connected.": "আপনার ওয়েবসাইট এবং ব্যবসার তথ্য সংযুক্ত রাখুন।",
  "Menu performance": "মেনু পারফরম্যান্স",
  "We miss you! Come back this week for a special offer.": "আমরা আপনাকে মিস করছি! এই সপ্তাহে একটি বিশেষ অফারের জন্য ফিরে আসুন।",
  "Campaign ready": "ক্যাম্পেইন প্রস্তুত",
  "Feature": "ফিচার",
  "Example insights": "উদাহরণ ইনসাইট",
  "Sales trend": "বিক্রয় ট্রেন্ড",
  "Positive": "ইতিবাচক",
  "Repeat customers": "রিপিট কাস্টমার",
  "Growing": "বাড়ছে",
  "English": "English",
  "BeezNest AI": "BeezNest AI",
  "Your business manager": "আপনার বিজনেস ম্যানেজার",
  "Ask your business": "আপনার ব্যবসাকে জিজ্ঞাসা করুন",
  "anything.": "যেকোনো কিছু।",
  "Get simple, useful answers from your business information without digging through multiple screens.": "একাধিক স্ক্রিন খোঁড়াখুঁড়ি না করে আপনার ব্যবসার তথ্য থেকে সহজ, প্রয়োজনীয় উত্তর পান।",
  "Which menu item has the best margin?": "কোন মেনু আইটেমের মার্জিন সবচেয়ে ভালো?",
  "Your Chicken Burger is currently one of the strongest margin items.": "আপনার চিকেন বার্গার বর্তমানে সবচেয়ে বেশি মার্জিনের আইটেমগুলোর একটি।",
  "How can I bring customers back?": "আমি কীভাবে কাস্টমারদের ফিরিয়ে আনতে পারি?",
  "Give me this week's summary.": "আমাকে এই সপ্তাহের সারাংশ দিন।",
  "Sales are trending positively. Your repeat-customer activity also improved.": "বিক্রয় ইতিবাচকভাবে বাড়ছে। আপনার রিপিট-কাস্টমার কার্যক্রমও উন্নত হয়েছে।",
  "AI Manager": "AI ম্যানেজার",
  "Example conversation": "উদাহরণ কথোপকথন",
  "Thinking about your business...": "আপনার ব্যবসা নিয়ে ভাবছি...",

  // --- AI MANAGER SPOTLIGHT ---
  "Your business has a": "আপনার ব্যবসার একজন ম্যানেজার আছে",
  "manager who never sleeps.": "যিনি কখনো ঘুমান না।",
  "Ask simple questions about your business and get useful answers without digging through reports, spreadsheets or multiple screens.": "আপনার ব্যবসা সম্পর্কে সহজ প্রশ্ন করুন এবং রিপোর্ট, স্প্রেডশিট বা একাধিক স্ক্রিন খোঁড়াখুঁড়ি না করে প্রয়োজনীয় উত্তর পান।",
  "Try asking": "জিজ্ঞাসা করে দেখুন",
  "Click to explore": "দেখতে ক্লিক করুন",
  "Designed to turn your business data into simple, actionable answers.": "আপনার ব্যবসার ডেটাকে সহজ, কার্যকর উত্তরে রূপান্তর করার জন্য ডিজাইন করা হয়েছে।",
  "Which product made the most profit this week?": "এই সপ্তাহে কোন পণ্য সবচেয়ে বেশি লাভ করেছে?",
  "Your Chicken Burger generated the strongest profit margin this week.": "এই সপ্তাহে আপনার চিকেন বার্গার সবচেয়ে বেশি লাভের মার্জিন তৈরি করেছে।",
  "How can I bring back inactive customers?": "আমি কীভাবে নিষ্ক্রিয় কাস্টমারদের ফিরিয়ে আনতে পারি?",
  "You could send a win-back offer to customers who have not ordered recently.": "যারা সম্প্রতি অর্ডার করেননি তাদের একটি উইন-ব্যাক অফার পাঠাতে পারেন।",
  "How is my business performing?": "আমার ব্যবসা কেমন চলছে?",
  "Your sales are trending upward and repeat customer activity is improving.": "আপনার বিক্রয় ঊর্ধ্বমুখী এবং রিপিট কাস্টমার কার্যক্রম উন্নত হচ্ছে।",
  "Weekly sales": "সাপ্তাহিক বিক্রয়",
  "12.8% from last week": "গত সপ্তাহ থেকে ১২.৮%",
  "Best margin": "সেরা মার্জিন",
  "Chicken Burger": "চিকেন বার্গার",
  "Profit margin": "লাভের মার্জিন",
  "BeezNest AI Manager": "BeezNest AI ম্যানেজার",
  "Online": "অনলাইন",
  "AI ASSISTANT": "AI সহকারী",
  "Analyzing your business...": "আপনার ব্যবসা বিশ্লেষণ করছি...",
  "Key insight": "মূল ইনসাইট",
  "Business snapshot": "ব্যবসার স্ন্যাপশট",
  "Looking healthy": "স্বাস্থ্যকর দেখাচ্ছে",
  "Ask about your business...": "আপনার ব্যবসা সম্পর্কে জিজ্ঞাসা করুন...",

  // --- WEBSITE BUILDER ---
  "Website builder": "ওয়েবসাইট বিল্ডার",
  "Your website.": "আপনার ওয়েবসাইট।",
  "Your brand.": "আপনার ব্র্যান্ড।",
  "Pick your colours and logo. We build the website for you — and when you update your menu in BeezNest, your website stays in sync.": "আপনার রং ও লোগো বেছে নিন। আমরা আপনার জন্য ওয়েবসাইট তৈরি করি — এবং আপনি যখন BeezNest-এ মেনু আপডেট করেন, আপনার ওয়েবসাইট সিঙ্কে থাকে।",
  "Make it look like your business.": "এটি আপনার ব্যবসার মতো দেখতে করুন।",
  "No complicated website editor. Choose a style, add your logo, and let BeezNest handle the rest.": "কোনো জটিল ওয়েবসাইট এডিটর নয়। একটি স্টাইল বেছে নিন, আপনার লোগো যোগ করুন এবং বাকি কাজ BeezNest-এর উপর ছেড়ে দিন।",
  "Choose your brand colours": "আপনার ব্র্যান্ডের রং বেছে নিন",
  "Add your logo and business details": "আপনার লোগো ও ব্যবসার তথ্য যোগ করুন",
  "Keep your menu synced automatically": "আপনার মেনু স্বয়ংক্রিয়ভাবে সিঙ্কে রাখুন",
  "Choose your colour": "আপনার রং বেছে নিন",
  "Click a colour to preview it live": "একটি রঙে ক্লিক করে সরাসরি প্রিভিউ দেখুন",
  "Website status": "ওয়েবসাইটের অবস্থা",
  "Live & synced": "লাইভ ও সিঙ্ক করা",
  "Mobile ready": "মোবাইল প্রস্তুত",
  "Always responsive": "সবসময় রেসপন্সিভ",
  "A polished website experience, connected to the same system that runs your business.": "একটি সুন্দর ওয়েবসাইট অভিজ্ঞতা, যা আপনার ব্যবসা পরিচালনার একই সিস্টেমের সঙ্গে সংযুক্ত।",
  "Bistro 24": "বিস্ট্রো ২৪",
  "Order now": "অর্ডার করুন",
  "About": "সম্পর্কে",
  "Contact": "যোগাযোগ",
  "Fresh every day": "প্রতিদিন তাজা",
  "Good food.": "ভালো খাবার।",
  "Good mood.": "ভালো অনুভূতি।",
  "Delicious meals made with fresh ingredients and served with care.": "তাজা উপকরণ দিয়ে যত্নসহকারে তৈরি সুস্বাদু খাবার।",
  "Explore menu": "মেনু দেখুন",
  "Popular today": "আজকের জনপ্রিয়",
  "Order": "অর্ডার",
  "Welcome": "স্বাগতম",
  "Taste the": "স্বাদের",
  "difference.": "পার্থক্য উপভোগ করুন।",
  "Today's favourites": "আজকের পছন্দ",
  "Synced": "সিঙ্কড",

  // --- WEBSITE BUILDER NEW TEXT (agency template) ---
  "Book consultation": "পরামর্শ বুক করুন",
  "Study abroad": "বিদেশে পড়াশোনা",
  "Your future starts here.": "আপনার ভবিষ্যৎ এখান থেকেই শুরু।",
  "Manage students, documents and applications from one place.": "এক জায়গা থেকে শিক্ষার্থী, ডকুমেন্ট ও আবেদন পরিচালনা করুন।",
  "Explore services": "সেবাগুলো দেখুন",
  "Application overview": "আবেদনের সংক্ষিপ্ত বিবরণ",
  "View pipeline": "পাইপলাইন দেখুন",
  "Student Application": "শিক্ষার্থীর আবেদন",
  "University application and document tracking": "বিশ্ববিদ্যালয়ের আবেদন ও ডকুমেন্ট ট্র্যাকিং",
  "Visa Documentation": "ভিসা ডকুমেন্টেশন",
  "Documents and application checklist": "ডকুমেন্ট ও আবেদন চেকলিস্ট",
  "New Student Lead": "নতুন শিক্ষার্থী লিড",
  "Follow-up and consultation required": "ফলো-আপ ও পরামর্শ প্রয়োজন",
  "In progress": "চলমান",
  "Quick links": "দ্রুত লিংক",
  "Plan your": "আপনার",
  "next step.": "পরবর্তী পদক্ষেপ।",

  // --- WEBSITE BUILDER – business-style customization ---
  "Make it look like your restaurant.": "আপনার রেস্টুরেন্টের মতো করে সাজান।",
  "Make it look like your agency.": "আপনার এজেন্সির মতো করে সাজান।",
  "Present your services, student journey and agency brand with a simple professional website.": "একটি সহজ ও প্রফেশনাল ওয়েবসাইটে আপনার সেবা, শিক্ষার্থীর যাত্রা এবং এজেন্সির ব্র্যান্ড তুলে ধরুন।",
  "Add your logo and agency details": "আপনার লোগো ও এজেন্সির তথ্য যোগ করুন",
  "Keep student and service information organized": "শিক্ষার্থী ও সেবার তথ্য সুন্দরভাবে সাজিয়ে রাখুন",
  "Use": "ব্যবহার করুন",
  "theme": "থিম",

  // --- Testimonials / Pilot section ---
  "Built with growing businesses": "বর্ধনশীল ব্যবসাগুলোর সঙ্গে তৈরি",
  "Built for the businesses we want to serve.": "যেসব ব্যবসার জন্য আমরা কাজ করতে চাই, তাদের জন্য তৈরি।",
  "We are still building our customer community. Instead of invented testimonials, we are sharing what BeezNest is being built around.": "আমরা এখনও আমাদের কাস্টমার কমিউনিটি তৈরি করছি। বানানো প্রশংসাপত্রের পরিবর্তে, BeezNest কোন বাস্তব প্রয়োজনকে কেন্দ্র করে তৈরি হচ্ছে তা আমরা শেয়ার করছি।",
  "Built from real business problems": "বাস্তব ব্যবসায়িক সমস্যা থেকে তৈরি",
  "BeezNest is being shaped around the everyday challenges of restaurants and agencies in Bangladesh.": "বাংলাদেশের রেস্টুরেন্ট ও এজেন্সিগুলোর প্রতিদিনের বাস্তব চ্যালেঞ্জকে কেন্দ্র করে BeezNest তৈরি হচ্ছে।",
  "Help us build it better": "আমাদের আরও ভালোভাবে তৈরি করতে সাহায্য করুন",
  "We are working with early businesses to understand what makes managing sales, customers and websites easier.": "সেলস, কাস্টমার ও ওয়েবসাইট পরিচালনা আরও সহজ করতে কী প্রয়োজন, তা বুঝতে আমরা প্রাথমিক পর্যায়ের ব্যবসাগুলোর সঙ্গে কাজ করছি।",
  "Join the early community": "প্রাথমিক কমিউনিটিতে যোগ দিন",
  "Be part of the pilot and help influence the features that matter most to growing businesses.": "পাইলট প্রোগ্রামের অংশ হয়ে উঠুন এবং বর্ধনশীল ব্যবসার জন্য সবচেয়ে গুরুত্বপূর্ণ ফিচারগুলো তৈরিতে সাহায্য করুন।",
  "Early-stage community": "প্রাথমিক পর্যায়ের কমিউনিটি",
  "Join our pilot": "আমাদের পাইলটে যোগ দিন",
  "Want to help shape BeezNest?": "BeezNest তৈরিতে সাহায্য করতে চান?",
  "Start with the tools you need today and help us make the product better for businesses like yours.": "আজ আপনার প্রয়োজনীয় টুলগুলো দিয়ে শুরু করুন এবং আপনার মতো ব্যবসার জন্য প্রোডাক্টটি আরও ভালো করতে আমাদের সাহায্য করুন।",
  "Join the pilot": "পাইলটে যোগ দিন",

  // --- FAQ ---
  "Still have questions?": "এখনো প্রশ্ন আছে?",
  "Chat with us and find the right way to get started with your business.": "আমাদের সাথে চ্যাট করুন এবং আপনার ব্যবসা শুরু করার সঠিক উপায় খুঁজে নিন।",
  "Chat with us": "আমাদের সাথে চ্যাট করুন",
  "Simple answers. No complicated jargon.": "সহজ উত্তর। কোনো জটিল পরিভাষা নেই।",
  "Answers, made simple": "উত্তর, সহজ করে",
  "Questions before you": "আপনি শুরু করার আগে",
  "get started?": "প্রশ্ন আছে?",
  "Here are the answers to the questions business owners usually have before getting started with BeezNest.": "ব্যবসার মালিকরা সাধারণত BeezNest শুরু করার আগে যে প্রশ্নগুলো করেন, তার উত্তর এখানে।",
  "What is BeezNest?": "BeezNest কী?",
  "BeezNest is an AI-powered business management platform designed to help restaurants and visa agencies manage important parts of their business from one workspace.": "BeezNest একটি AI-চালিত ব্যবসা ব্যবস্থাপনা প্ল্যাটফর্ম, যা রেস্টুরেন্ট এবং ভিসা এজেন্সিগুলোকে একটি ওয়ার্কস্পেস থেকে তাদের ব্যবসার গুরুত্বপূর্ণ অংশগুলো পরিচালনা করতে সাহায্য করার জন্য ডিজাইন করা হয়েছে।",
  "Who is BeezNest made for?": "BeezNest কাদের জন্য তৈরি?",
  "BeezNest is designed for restaurants and visa agencies. You can choose your business type during sign-up and use the experience built around that business.": "BeezNest রেস্টুরেন্ট এবং ভিসা এজেন্সির জন্য ডিজাইন করা হয়েছে। সাইন-আপের সময় আপনি আপনার ব্যবসার ধরন বেছে নিতে পারেন এবং সেই ব্যবসাকে কেন্দ্র করে তৈরি অভিজ্ঞতা ব্যবহার করতে পারেন।",
  "Can I manage my website and business from one place?": "আমি কি এক জায়গা থেকে আমার ওয়েবসাইট এবং ব্যবসা পরিচালনা করতে পারি?",
  "Yes. BeezNest is designed to connect your website experience with your business management tools, so important information can stay in sync.": "হ্যাঁ। BeezNest আপনার ওয়েবসাইট অভিজ্ঞতাকে আপনার ব্যবসা ব্যবস্থাপনা টুলের সাথে সংযুক্ত করার জন্য ডিজাইন করা হয়েছে, যাতে গুরুত্বপূর্ণ তথ্য সিঙ্কে থাকতে পারে।",
  "Does my website update when I change my menu?": "আমি মেনু পরিবর্তন করলে আমার ওয়েবসাইট আপডেট হয়?",
  "The website builder demo shows how your restaurant website can stay connected to your menu. When you change the menu, the website can reflect those changes.": "ওয়েবসাইট বিল্ডার ডেমো দেখায় কীভাবে আপনার রেস্টুরেন্টের ওয়েবসাইট আপনার মেনুর সাথে সংযুক্ত থাকতে পারে। আপনি মেনু পরিবর্তন করলে ওয়েবসাইট সেই পরিবর্তন প্রতিফলিত করতে পারে।",
  "Can I use BeezNest in Bangla and English?": "আমি কি বাংলা এবং ইংরেজিতে BeezNest ব্যবহার করতে পারি?",
  "Yes. Bangla and English are part of the product experience, making BeezNest easier to use for businesses in Bangladesh.": "হ্যাঁ। বাংলা এবং ইংরেজি পণ্যের অভিজ্ঞতার অংশ, যা বাংলাদেশের ব্যবসার জন্য BeezNest ব্যবহার করা সহজ করে তোলে।",
  "What can the AI business manager help me with?": "AI বিজনেস ম্যানেজার আমাকে কীভাবে সাহায্য করতে পারে?",
  "The AI manager is designed to help you understand your business information and answer questions such as which products performed best, how to bring back inactive customers, and how your business is performing.": "AI ম্যানেজার আপনার ব্যবসার তথ্য বুঝতে এবং কোন পণ্যগুলো সবচেয়ে ভালো পারফর্ম করেছে, কীভাবে নিষ্ক্রিয় কাস্টমারদের ফিরিয়ে আনা যায়, এবং আপনার ব্যবসা কেমন চলছে ইত্যাদি প্রশ্নের উত্তর দিতে সাহায্য করার জন্য ডিজাইন করা হয়েছে।",
  "How do I choose the right plan?": "আমি কীভাবে সঠিক প্ল্যান বেছে নেব?",
  "Start with the pricing preview and choose the business type that matches your business. You can compare the available plans and features before getting started.": "প্রাইসিং প্রিভিউ দিয়ে শুরু করুন এবং আপনার ব্যবসার সাথে মানানসই ব্যবসার ধরন বেছে নিন। শুরু করার আগে আপনি উপলব্ধ প্ল্যান এবং ফিচার তুলনা করতে পারেন।",
  "How do I get started?": "আমি কীভাবে শুরু করব?",
  "Choose Start free trial and follow the sign-up steps. You will create your account, verify your phone, and choose your business type.": "Start free trial বেছে নিন এবং সাইন-আপের ধাপগুলো অনুসরণ করুন। আপনি আপনার অ্যাকাউন্ট তৈরি করবেন, আপনার ফোন যাচাই করবেন এবং আপনার ব্যবসার ধরন বেছে নেবেন।",

  // --- FINAL CTA ---
  "Start growing smarter": "আরও স্মার্টভাবে বাড়া শুরু করুন",
  "Ready to run your": "আপনার ব্যবসা আরও স্মার্টভাবে",
  "business smarter?": "চালাতে প্রস্তুত?",
  "Bring your sales, customers, operations and business insights together in one simple workspace.": "আপনার বিক্রয়, কাস্টমার, অপারেশন এবং ব্যবসায়িক ইনসাইট একটি সহজ ওয়ার্কস্পেসে একত্রিত করুন।",
  "See pricing": "মূল্য দেখুন",
  "Your business data stays private and protected.": "আপনার ব্যবসার ডেটা গোপন ও সুরক্ষিত থাকে।",
  "Overview": "ওভারভিউ",
  "Good morning ": "শুভ সকাল ",
  "Sales performance": "বিক্রয় পারফরম্যান্স",
  "This month": "এই মাস",
  "Win back 14 customers": "১৪ জন কাস্টমার ফিরিয়ে আনুন",

  // --- PRICING PREVIEW ---
  "Simple pricing": "সহজ মূল্য নির্ধারণ",
  "Plans that grow with": "আপনার ব্যবসার সাথে বাড়ে",
  "your business.": "এমন প্ল্যান।",
  "Plans that grow with your business.": "আপনার ব্যবসার সাথে বাড়ে এমন প্ল্যান।",
  "Start with what you need today and move up when your business is ready.": "আজ আপনার যা প্রয়োজন তা দিয়ে শুরু করুন এবং ব্যবসা প্রস্তুত হলে এগিয়ে যান।",
  "Choose the tools that fit your business today. You can change your plan as your business grows.": "আজ আপনার ব্যবসার সাথে মানানসই টুলগুলো বেছে নিন। ব্যবসা বাড়ার সাথে সাথে আপনি আপনার প্ল্যান পরিবর্তন করতে পারেন।",
  "Restaurant": "রেস্টুরেন্ট",
  "Visa agency": "ভিসা এজেন্সি",
  "Monthly": "মাসিক",
  "Yearly": "বার্ষিক",
  "Save": "সাশ্রয়",
  "Most popular": "সবচেয়ে জনপ্রিয়",
  "What's included": "যা যা থাকছে",
  "Includes": "যা যা থাকছে",
  "For restaurants": "রেস্টুরেন্টের জন্য",
  "For visa agencies": "ভিসা এজেন্সির জন্য",
  "Start free trial": "ফ্রি ট্রায়াল শুরু করুন",
  "Need help choosing a plan?": "প্ল্যান বেছে নিতে সাহায্য প্রয়োজন?",
  "Compare all plans": "সব প্ল্যান তুলনা করুন",
  "Compare plans": "প্ল্যান তুলনা করুন",
  "Restaurant plan comparison": "রেস্টুরেন্ট প্ল্যান তুলনা",
  "Visa agency plan comparison": "ভিসা এজেন্সি প্ল্যান তুলনা",
  "Toggle comparison": "তুলনা টগল করুন",
  "For small restaurants getting started.": "শুরু করা ছোট রেস্টুরেন্টের জন্য।",
  "For growing restaurants that want more control.": "আরও নিয়ন্ত্রণ চাওয়া বর্ধনশীল রেস্টুরেন্টের জন্য।",
  "For busy restaurants ready to scale.": "স্কেল করতে প্রস্তুত ব্যস্ত রেস্টুরেন্টের জন্য।",
  "For agencies organizing their daily workflow.": "তাদের দৈনন্দিন ওয়ার্কফ্লো সাজানো এজেন্সিগুলোর জন্য।",
  "For agencies managing more clients and leads.": "আরও ক্লায়েন্ট ও লিড পরিচালনা করা এজেন্সিগুলোর জন্য।",
  "For established agencies with larger teams.": "বড় টিমসহ প্রতিষ্ঠিত এজেন্সিগুলোর জন্য।",
  "Digital menu": "ডিজিটাল মেনু",
  "Customer management": "কাস্টমার ম্যানেজমেন্ট",
  "Basic sales reports": "বেসিক বিক্রয় রিপোর্ট",
  "QR ordering": "QR অর্ডারিং",
  "Everything in Starter": "Starter-এর সবকিছু",
  "Website builder": "ওয়েবসাইট বিল্ডার",
  "Smart win-back campaigns": "স্মার্ট উইন-ব্যাক ক্যাম্পেইন",
  "AI business manager": "AI বিজনেস ম্যানেজার",
  "Advanced reports": "অ্যাডভান্সড রিপোর্ট",
  "Multi-location support": "মাল্টি-লোকেশন সাপোর্ট",
  "Advanced customer insights": "অ্যাডভান্সড কাস্টমার ইনসাইট",
  "Priority support": "প্রায়োরিটি সাপোর্ট",
  "Team management": "টিম ম্যানেজমেন্ট",
  "Lead management": "লিড ম্যানেজমেন্ট",
  "Client profiles": "ক্লায়েন্ট প্রোফাইল",
  "Basic reports": "বেসিক রিপোর্ট",
  "Task tracking": "টাস্ক ট্র্যাকিং",
  "Lead follow-ups": "লিড ফলো-আপ",
  "Advanced client insights": "অ্যাডভান্সড ক্লায়েন্ট ইনসাইট",
  "Multiple workflows": "একাধিক ওয়ার্কফ্লো",
  "/month": "/মাস",
  "/year": "/বছর",
  "Billed yearly · save more": "বার্ষিক বিল · আরও সাশ্রয়",
  "Expand when your business needs more": "ব্যবসার প্রয়োজন বাড়লে আরও সুবিধা নিন",
  "Start with the plan that fits your needs and add more capabilities as your business grows.": "আপনার প্রয়োজন অনুযায়ী প্ল্যান দিয়ে শুরু করুন এবং ব্যবসা বাড়ার সাথে সাথে আরও সুবিধা যোগ করুন।",
  "Additional SMS credits": "অতিরিক্ত SMS ক্রেডিট",
  "Custom domain": "কাস্টম ডোমেইন",
  "Advanced AI usage": "অ্যাডভান্সড AI ব্যবহার",
  "Extra website customization": "অতিরিক্ত ওয়েবসাইট কাস্টমাইজেশন",
  "Not sure which plan is right for you?": "কোন প্ল্যান আপনার জন্য সঠিক তা নিশ্চিত নন?",
  "Start with the plan that matches your current needs. You can change your plan as your business grows.": "আপনার বর্তমান প্রয়োজন অনুযায়ী প্ল্যান দিয়ে শুরু করুন। ব্যবসা বাড়ার সাথে সাথে আপনি আপনার প্ল্যান পরিবর্তন করতে পারেন।",
  "Back to home": "হোমে ফিরে যান",
  "Billing cycle": "বিলিং চক্র",
  "One simple workspace for growing businesses. Manage your operations, understand your numbers and make smarter decisions.": "বর্ধনশীল ব্যবসার জন্য একটি সহজ ওয়ার্কস্পেস। আপনার কার্যক্রম পরিচালনা করুন, আপনার সংখ্যা বুঝুন এবং আরও স্মার্ট সিদ্ধান্ত নিন।",
  "Phone coming soon": "ফোন নম্বর শীঘ্রই যোগ করা হবে।",
  "Payment methods may vary by plan.": "প্ল্যান অনুযায়ী পেমেন্ট পদ্ধতি ভিন্ন হতে পারে।",

  // --- MOCK DASHBOARD ---
  "Business Overview": "ব্যবসায়িক ওভারভিউ",
  "Agency Overview": "এজেন্সি ওভারভিউ",
  "Applications": "আবেদন",
  "Conversion": "কনভার্সন",
  "Application pipeline": "আবেদন পাইপলাইন",
  "Recent applications": "সাম্প্রতিক আবেদন",
  "Visa file": "ভিসা ফাইল",
  "Documents": "ডকুমেন্ট",
  "5 follow-ups suggested": "৫টি ফলো-আপ প্রয়োজন",
  "Prioritize pending documents and follow-ups.": "পেন্ডিং ডকুমেন্ট ও ফলো-আপগুলো আগে করুন।",
  "Increase repeat orders with your best-selling combo.": "আপনার সেরা কম্বো দিয়ে রিপিট অর্ডার বাড়ান।",
  "3 opportunities found": "৩টি সম্ভাবনা পাওয়া গেছে",

  // --- AUTH / LOGIN / SIGNUP ---
  "Welcome back": "আবার স্বাগতম",
  "Run your business with confidence.": "আত্মবিশ্বাসের সাথে আপনার ব্যবসা পরিচালনা করুন।",
  "Sign in to manage your business, customers, sales, and smart insights from one workspace.": "একটি ওয়ার্কস্পেস থেকে আপনার ব্যবসা, কাস্টমার, বিক্রয় এবং স্মার্ট ইনসাইট পরিচালনা করতে সাইন ইন করুন।",
  "Secure business access": "নিরাপদ ব্যবসায়িক অ্যাক্সেস",
  "Login to continue protecting and growing your business.": "আপনার ব্যবসা সুরক্ষিত রাখতে এবং বাড়াতে লগইন করুন।",
  "Email or phone number": "ইমেইল বা ফোন নম্বর",
  "Password": "পাসওয়ার্ড",
  "Forgot password?": "পাসওয়ার্ড ভুলে গেছেন?",
  "Enter your password": "আপনার পাসওয়ার্ড লিখুন",
  "Sign in": "সাইন ইন",
  "Signing in...": "সাইন ইন করছি...",
  "or continue with": "অথবা চালিয়ে যান",
  "Continue with Google": "Google দিয়ে চালিয়ে যান",
  "Don't have an account?": "অ্যাকাউন্ট নেই?",
  "Create an account": "একটি অ্যাকাউন্ট তৈরি করুন",
  "Your business information stays protected.": "আপনার ব্যবসার তথ্য সুরক্ষিত থাকে।",
  "Start your journey": "আপনার যাত্রা শুরু করুন",
  "Build a smarter business.": "একটি স্মার্ট ব্যবসা তৈরি করুন।",
  "Create your BeezNest account in three simple steps.": "তিনটি সহজ ধাপে আপনার BeezNest অ্যাকাউন্ট তৈরি করুন।",
  "Your setup": "আপনার সেটআপ",
  "Verify your phone": "আপনার ফোন যাচাই করুন",
  "Choose your business": "আপনার ব্যবসা বেছে নিন",
  "Create account": "অ্যাকাউন্ট তৈরি করুন",
  "Verify phone": "ফোন যাচাই করুন",
  "Business type": "ব্যবসার ধরন",
  "Your name": "আপনার নাম",
  "Business name": "ব্যবসার নাম",
  "Phone number": "ফোন নম্বর",
  "Email address": "ইমেইল ঠিকানা",
  "I agree to the": "আমি সম্মত আছি",
  "Terms": "শর্তাবলী",
  "and": "এবং",
  "Privacy Policy": "প্রাইভেসি পলিসি",
  "Check your phone": "আপনার ফোন চেক করুন",
  "We sent a 6-digit verification code to": "আমরা একটি ৬ সংখ্যার ভেরিফিকেশন কোড পাঠিয়েছি",
  "Enter verification code": "ভেরিফিকেশন কোড লিখুন",
  "Resend in": "আবার পাঠান",
  "Resend code": "কোড আবার পাঠান",
  "Change number": "নম্বর পরিবর্তন করুন",
  "Phone verified!": "ফোন ভেরিফাইড!",
  "Your phone number has been successfully verified.": "আপনার ফোন নম্বর সফলভাবে ভেরিফাই করা হয়েছে।",
  "Tell us what kind of business you want to manage with BeezNest.": "আপনি BeezNest দিয়ে কোন ধরনের ব্যবসা পরিচালনা করতে চান তা জানান।",
  "Manage orders, tables, customers, menu and reports.": "অর্ডার, টেবিল, কাস্টমার, মেনু এবং রিপোর্ট পরিচালনা করুন।",
  "Manage leads, documents, applications and follow-ups.": "লিড, ডকুমেন্ট, আবেদন এবং ফলো-আপ পরিচালনা করুন।",
  "Restaurant selected": "রেস্টুরেন্ট নির্বাচিত",
  "Visa Agency selected": "ভিসা এজেন্সি নির্বাচিত",
  "Back": "পেছনে",
  "Please wait...": "অনুগ্রহ করে অপেক্ষা করুন...",
  "Verify & continue": "ভেরিফাই করে এগিয়ে যান",
  "Finish setup": "সেটআপ সম্পন্ন করুন",
  "Already have an account?": "ইতিমধ্যে একটি অ্যাকাউন্ট আছে?",
  "Log in": "লগ ইন",
  "Secure account setup": "নিরাপদ অ্যাকাউন্ট সেটআপ",
  "One workspace for your": "আপনার সমগ্র ব্যবসার জন্য",
  "whole business.": "একটি ওয়ার্কস্পেস।",
  "Bring your business tools, customer information and daily operations together with BeezNest.": "BeezNest-এর সাথে আপনার ব্যবসায়িক টুল, কাস্টমার তথ্য এবং দৈনন্দিন কার্যক্রম একত্রিত করুন।",
  "Your business has a manager that": "আপনার ব্যবসার একজন ম্যানেজার আছে যে",
  "never sleeps.": "কখনো ঘুমায় না।",
  "See your business clearly, understand what is happening, and make better decisions from one place.": "আপনার ব্যবসা স্পষ্টভাবে দেখুন, কী ঘটছে তা বুঝুন এবং এক জায়গা থেকে আরও ভালো সিদ্ধান্ত নিন।",
  "Business overview": "ব্যবসায়িক ওভারভিউ",
  "This week": "এই সপ্তাহ",
  "AI Business Manager": "AI বিজনেস ম্যানেজার",
  "Your next business insight is one click away.": "আপনার পরবর্তী ব্যবসায়িক ইনসাইট এক ক্লিক দূরে।",
  "3 opportunities found for your business.": "আপনার ব্যবসার জন্য ৩টি সম্ভাবনা পাওয়া গেছে।",
  "New order": "নতুন অর্ডার",
  "Sales today": "আজকের বিক্রয়",
  "Growing steadily": "ধারাবাহিকভাবে বাড়ছে",
  "Smart insights": "স্মার্ট ইনসাইট",

  // --- FOOTER ---
  "Business management made simple.": "ব্যবসা পরিচালনা এখন আরও সহজ।",
  "Product": "প্রোডাক্ট",
  "Company": "কোম্পানি",
  "Legal": "আইনি",
  "Customers": "কাস্টমার",
  "Contact": "যোগাযোগ",
  "Get started": "শুরু করুন",
  "Start managing your business smarter.": "আরও স্মার্টভাবে আপনার ব্যবসা পরিচালনা শুরু করুন।",
  "All rights reserved.": "সর্বস্বত্ব সংরক্ষিত।",
  "Privacy": "প্রাইভেসি",
  "Terms": "শর্তাবলী",
  "Back to top": "উপরে ফিরে যান",
  "Privacy Policy": "প্রাইভেসি পলিসি",
  "Terms of Service": "সেবার শর্তাবলী",
  "Cookie Policy": "কুকি পলিসি",
  "About us": "আমাদের সম্পর্কে",
  "Blog": "ব্লগ",
  "Payments": "পেমেন্ট",
  "Follow us": "আমাদের অনুসরণ করুন",
  "Made for businesses in Bangladesh.": "বাংলাদেশের ব্যবসার জন্য তৈরি।",

  // --- PRICING PAGE ---
  "Simple plans for growing businesses": "বর্ধনশীল ব্যবসার জন্য সহজ প্ল্যান",
  "Choose your business type and find the plan that fits your current stage.": "আপনার ব্যবসার ধরন নির্বাচন করুন এবং বর্তমান অবস্থার জন্য উপযুক্ত প্ল্যান বেছে নিন।",
  "/year": "/বছর",
  "Recommended": "সুপারিশকৃত",
  "Includes:": "যা যা থাকছে:",
  "Choose the plan that fits your business.": "আপনার ব্যবসার জন্য উপযুক্ত প্ল্যান বেছে নিন।",
  "Add-ons": "অ্যাড-অন",
  "OR": "অথবা",
  "View pricing": "মূল্য দেখুন",
  "Join the pilot": "পাইলটে যোগ দিন",
  "Built with real business needs in mind.": "প্রকৃত ব্যবসায়িক চাহিদার কথা মাথায় রেখে তৈরি।",
  "We are opening our pilot to restaurant and visa agency owners in Bangladesh.": "আমরা বাংলাদেশের রেস্টুরেন্ট এবং ভিসা এজেন্সি মালিকদের জন্য আমাদের পাইলট খুলছি।",
  "Questions, answered": "আপনার প্রশ্নের উত্তর",
  "FAQ": "সাধারণ প্রশ্ন",
  "Ready to grow?": "ব্যবসা আরও বড় করতে প্রস্তুত?",
  "Run your business with less busywork.": "কম ঝামেলায় আপনার ব্যবসা পরিচালনা করুন।",
  "Start managing your business smarter with BeezNest.": "BeezNest-এর মাধ্যমে আরও স্মার্টভাবে আপনার ব্যবসা পরিচালনা শুরু করুন।",
  "Explore features": "ফিচার দেখুন",
  "No credit card required": "কোনো ক্রেডিট কার্ড প্রয়োজন নেই",

  // --- AI MANAGER SPOTLIGHT (new keys) ---
  "Business activity": "ব্যবসায়িক কার্যক্রম",
  "Returning customers": "ফিরে আসা কাস্টমার",
  "AI insights": "AI ইনসাইট",
  "Powered by your business data": "আপনার ব্যবসার ডেটা দ্বারা পরিচালিত",
  "Trending positively": "ইতিবাচকভাবে বাড়ছে",

  // --- PRICING PAGE FINAL CTA ---
  "Not sure which plan to choose?": "কোন প্ল্যান বেছে নেবেন বুঝতে পারছেন না?",
  "Start with the trial and choose the plan that fits your business as you grow.": "ট্রায়াল দিয়ে শুরু করুন এবং ব্যবসা বাড়ার সাথে সাথে আপনার জন্য উপযুক্ত প্ল্যান বেছে নিন।",
  "Back to home": "হোমে ফিরে যান",
  "Billing cycle": "বিলিং চক্র",
  "One simple workspace for growing businesses. Manage your operations, understand your numbers and make smarter decisions.": "বর্ধনশীল ব্যবসার জন্য একটি সহজ ওয়ার্কস্পেস। আপনার কার্যক্রম পরিচালনা করুন, আপনার সংখ্যা বুঝুন এবং আরও স্মার্ট সিদ্ধান্ত নিন।",
  "Phone coming soon": "ফোন নম্বর শীঘ্রই যোগ করা হবে।",
  "Payment methods may vary by plan.": "প্ল্যান অনুযায়ী পেমেন্ট পদ্ধতি ভিন্ন হতে পারে।",

  "Grow with confidence.": "আত্মবিশ্বাসের সাথে বাড়ুন।",
 "Bring your customers, website, business tools and AI assistance together with BeezNest.": "আপনার কাস্টমার, ওয়েবসাইট, ব্যবসায়িক টুল এবং AI সহায়তা BeezNest-এর সাথে একত্রিত করুন।",
 "Explore pricing": "মূল্য দেখুন",
 "Built for Bangladesh": "বাংলাদেশের জন্য তৈরি",
 "Restaurant & Visa agency": "রেস্টুরেন্ট ও ভিসা এজেন্সি",
 "Your business at a glance.": "এক নজরে আপনার ব্যবসা।",
 "Last 30 days": "গত ৩০ দিন",
 "3 useful insights": "৩টি প্রয়োজনীয় ইনসাইট",
};

export function LanguageProvider({ children }) {
  const [language, setLanguageState] = useState(
    () => localStorage.getItem("beeznest_language") || "en"
  );

  const setLanguage = (nextLanguage) => {
    const next = nextLanguage === "bn" ? "bn" : "en";
    localStorage.setItem("beeznest_language", next);
    setLanguageState(next);
    document.documentElement.lang = next;
  };

  const t = (text) => {
    if (language === "bn") {
      return bn[text] || text;
    }
    return text;
  };

  const value = useMemo(
    () => ({ language, setLanguage, isBangla: language === "bn", t }),
    [language]
  );

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used inside LanguageProvider");
  }
  return context;
}